### ISSUE TITLE
Plugin in project

### ISSUE THREAD

**Issue by Lectem** [marynate/FluidSurface#2]
Would it be possible to have this plugin as a projet plugin ?
I tried adding '"CanContainContent" : true' descriptor to the .uplugin file, and putting the shaders in the Content folder, but it didn't work.
Is installing the shaders in the Engine folder the only way around it ?

**Comment by marynate** [comment]
Sorry for replay late. Unreal Engine don't support shaders in plugin now, so you have to put custom shders in Engine's shader directory.
As the plugin itself, it can be use as project plugin as long as the shader putted inside engine directory.
