### ISSUE TITLE
how to migrate to ue4.22?

### ISSUE THREAD

**Issue by KnIfER** [marynate/FluidSurface#7]
Using landscape module as a reference I have gotten the source compiled. 
But I cannot google a clue to fix the following shader errror:

    Shader compiler errors compiling WorldGridMaterial for platform PCD3D_SM5:
    D:/Code/FigureOut/simplest_srcmdl2/Shaders/Private/FluidSurfaceVertexFactory.ush(227,21-29): Shader FVelocityPS, Permutation 0, VF FFluidSurfaceVertexFactory:
	 error X3004: undeclared identifier 'Primitive'

The context is :   
```
half3x3 CalcTangentToWorldNoScale(in half3x3 TangentToLocal)
{
	half3x3 LocalToWorld = GetLocalToWorld3x3();
	half3 InvScale = Primitive.InvNonUniformScale.xyz;   //    <----
	LocalToWorld[0] *= InvScale.x;
	LocalToWorld[1] *= InvScale.y;
	LocalToWorld[2] *= InvScale.z;
	return mul(TangentToLocal, LocalToWorld); 
}
```
Even if I replace all 'Primitive' with `GetPrimitiveData(Parameters.PrimitiveId)` the compiler will still prompt me for the same error.

**Comment by KnIfER** [comment]
Primitive.InvNonUniformScale is renamed to Primitive.InvNonUniformScaleAndDeterminantSign

now I get this error: 
![Screenshot (15)](https://user-images.githubusercontent.com/11593903/59965723-797c1300-9544-11e9-9a6c-c5074d11001d.png)

**Comment by KnIfER** [comment]
done. https://github.com/KnIfER/FluidSurface-ue4.22

**Comment by gallonmate** [comment]
> 
> 
> done. https://github.com/KnIfER/FluidSurface-ue4.22

Did you delete your plugin? Can you make it public again?
